SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `qing`.`qb_posts` CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `qing`.`qb_tags` CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `qing`.`qb_like` CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `qing`.`qb_images` CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `qing`.`qb_users` CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `qing`.`qb_sites` CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `qing`.`qb_comments` CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
